name: audio_service
description: Flutter plugin to play audio in the background while the screen is off.
version: 0.17.0
homepage: https://github.com/ryanheise/audio_service

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  audio_session: ^0.1.0
  rxdart: ^0.26.0
  flutter_isolate: ^2.0.0
  flutter_cache_manager: ^3.0.0
  js: ^0.6.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.audioservice
        pluginClass: AudioServicePlugin
      ios:
        pluginClass: AudioServicePlugin
      macos:
        pluginClass: AudioServicePlugin
      web:
        pluginClass: AudioServicePlugin
        fileName: audio_service_web.dart
